dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: nArCChApXcvuy4nyDKtKeWYYXyt30hcowuJEqfJglho5DI+nZhRW1qjIzavnY0ExKVASIO0Y3622IveMU2gRKRO8UEBODUp3P/d0/fCJCmLB9LgGLI7NknzqWvKaUOUPPeCCZKFf7pGb6MhRfFrLMxZfU+KrgXfWErEdL5aE9Mm9HcBAr8hshzh5gFzSXRr7oyzU7WPQT5J/kK6Op9Fk6ND9recoLA5VZU6d2VuXYRsuZtTYvtwwoNIy5VyJUCrXytn4RSyHCdN4x2RDK0MNKlT03WumqZVg73S1X1ePH6OpfAP99KTNfdtpTLT2/t64jbfs26yL2tKa2HhzNsZkjYf6yIgl6sdrazxJPtG1VHAFZsKn9qQsGQBObLJ+ItBzjbo/wHA0+ipEkwOModPr81tDjfRGsMzPO0y6PHKlVnO3P9kMp6IdlrMYsfvJBG0m6Vq6OLugO93mVLPT1XWc6zI0Qx1hgE59tMUjcD4Qsz8hyZT4N7LmbkpPp3z6hEcMjJk8DvKWfQVtIp7ke8IkvY3Q/rkAiAqYkrtZWJ6IOWjyIwUOwG1/mf7QDIx3RdgB3vlajwxeClaosq51a26l8+nN30dxX+Hx4jbtsHdbNbIEC2dMbOUHgJ7K3uDiiXiylAsq5KegDpux6ed+2KOZSQMlMovcUValjWRGV4ihzJs=
  file: Gerbers/PRO-115_gerbers.zip
  on:
    repo: w4xzr/PRO-115
  skip_cleanup: 'true'
